import type { Metadata } from 'next'
import Link from 'next/link'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://roofangler.com'

export const metadata: Metadata = {
  title: 'Disclaimer',
  description:
    'Disclaimer for Roof Pitch Calculator. All calculations should be verified by a licensed professional.',
  alternates: { canonical: `${SITE_URL}/disclaimer` },
}

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-12">
      <Link href="/" className="mb-6 text-sm text-muted">
        ← Back to Home
      </Link>

      <h1 className="text-3xl font-bold text-primary mb-2">Disclaimer</h1>
      <p className="text-sm text-muted mb-8">Last Updated: April 29, 2026</p>

      <h2 className="text-xl font-bold text-primary mt-8 mb-3">Professional Advice Disclaimer</h2>
      <p className="text-muted leading-relaxed mb-4">
        The Roof Pitch Calculator is designed to provide general mathematical estimates for
        educational and planning purposes only. It is not a replacement for professional
        roofing advice, structural engineering assessment, or on-site inspection by a qualified
        contractor.
      </p>
      <p className="text-muted leading-relaxed mb-4">
        All results produced by this tool should be reviewed and verified by a licensed roofing
        contractor or structural engineer before any construction work begins, materials are
        purchased, or financial commitments are made. Roof structure, local climate, building
        codes, and site-specific conditions can significantly affect appropriate pitch
        requirements and material specifications in ways this calculator cannot account for.
      </p>

      <h2 className="text-xl font-bold text-primary mt-8 mb-3">Accuracy of Results</h2>
      <p className="text-muted leading-relaxed mb-4">
        Results generated by Roof Pitch Calculator are based on standard trigonometric and
        geometric formulas for roof pitch, slope, and related measurements. The mathematical
        formulas themselves are correct; however, the accuracy of any output is entirely
        dependent on the accuracy of the values you provide as inputs.
      </p>
      <p className="text-muted leading-relaxed mb-4">
        Additionally, calculations do not account for:
      </p>
      <ul className="list-disc pl-6 text-muted leading-relaxed mb-4 space-y-1">
        <li>Local building codes and minimum pitch requirements by jurisdiction</li>
        <li>Material-specific installation requirements (e.g. minimum pitch for asphalt shingles vs. metal roofing)</li>
        <li>Snow load, wind uplift, or other regional weather factors</li>
        <li>Structural capacity of existing rafters or trusses</li>
        <li>Overhang, flashing, or drainage design requirements</li>
      </ul>
      <p className="text-muted leading-relaxed mb-4">
        Always consult applicable building codes and a licensed professional for project-specific
        guidance.
      </p>

      <h2 className="text-xl font-bold text-primary mt-8 mb-3">No Liability</h2>
      <p className="text-muted leading-relaxed mb-4">
        Roof Pitch Calculator and its operators expressly disclaim all liability for any loss,
        injury, damage, or expense — direct or indirect — that arises from reliance on the
        information or calculations provided by this site. This includes, without limitation:
      </p>
      <ul className="list-disc pl-6 text-muted leading-relaxed mb-4 space-y-1">
        <li>Construction defects or failures resulting from incorrect pitch application</li>
        <li>Property damage caused by an incorrectly specified or installed roof</li>
        <li>Financial loss from over- or under-ordering materials</li>
        <li>Personal injury arising from construction work undertaken using these estimates</li>
      </ul>
      <p className="text-muted leading-relaxed mb-4">
        Use of this tool is entirely at your own risk.
      </p>

      <h2 className="text-xl font-bold text-primary mt-8 mb-3">Affiliate Disclosure</h2>
      <p className="text-muted leading-relaxed mb-4">
        This site may in the future display affiliate links to roofing products, tools, or
        services. If and when such links are present, they will be clearly identified as
        affiliate or sponsored links. Clicking an affiliate link and making a purchase may earn
        us a commission at no additional cost to you. Our editorial content and calculation
        results are not influenced by affiliate relationships.
      </p>

      <h2 className="text-xl font-bold text-primary mt-8 mb-3">External Links</h2>
      <p className="text-muted leading-relaxed mb-4">
        This site may include links to external websites for reference or convenience. These
        links are provided in good faith, but we do not endorse, control, or take responsibility
        for the accuracy, legality, or content of any external site. Clicking an external link
        and leaving roofangler.com is done at your own discretion. We recommend
        reviewing the privacy policy and terms of any external site you visit.
      </p>
    </div>
  )
}
